// This code autogenerated by AnalyticsEventGeneratorEditor

namespace Modules.Analytics.Generated
{
   public interface IAnalyticParametersCollection 
   {
       int GetTimestamp (int defaultValue);
        //"user_id", Parameter still not in used in analytics systems, because there is no default value. This feature come from product side.
       string GetPlatform (string defaultValue);
       string GetAppVersion (string defaultValue);
       string GetDevice (string defaultValue);
       string GetOs (string defaultValue);
        //"ip", Parameter still not in used in analytics systems, because there is no default value. This feature come from product side.
        //"ltv", Parameter still not in used in analytics systems, because there is no default value. This feature come from product side.
        //"league", Parameter still not in used in analytics systems, because there is no default value. This feature come from product side.
        //"league_rank", Parameter still not in used in analytics systems, because there is no default value. This feature come from product side.
       string GetErrStr (string defaultValue);
       string GetWalletId (string defaultValue);
       int GetHcBalance (int defaultValue);
       int GetHcPaidBalance (int defaultValue);
       float GetLoadingTimeSec (float defaultValue);
       string GetGuiType (string defaultValue);
       string GetGameId (string defaultValue);
       string GetGameMode (string defaultValue);
       string GetOponenetId (string defaultValue);
       int GetOponenetRank (int defaultValue);
       string GetMyteamId (string defaultValue);
       int GetMyteamRank (int defaultValue);
       int GetScore (int defaultValue);
       float GetGameDurationSec (float defaultValue);
       int GetPlayerShoots (int defaultValue);
       int GetPlayerGoals (int defaultValue);
       int GetFoulsCommitedByPlayer (int defaultValue);
       int GetOponenetShoots (int defaultValue);
       int GetOponenetGoals (int defaultValue);
       int GetFoulsCommitedByOponenet (int defaultValue);
       int GetTotalTurns (int defaultValue);
   }
}
