- uses: game-ci/unity-test-runner@v4
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  with:
    projectPath: Galaga
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    unityVersion: 2022.2.7f1
    testMode: editmode
